platform :ios, '9.0'

target 'AudioTest' do
  use_frameworks!
pod 'HPRecorder'

end

target 'AudioTest WatchKit App' do
    use_frameworks!

end

target 'AudioTest WatchKit Extension' do
  use_frameworks!
pod 'HPRecorder'

end
